package prisonbreak;
import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.net.URL;
import java.util.*;
/**
@author Carson Lam
@version 1.1.0

Image sources:
https://pixeljoint.com/pixelart/78143.htm
https://www.vecteezy.com/vector-art/5450186-hand-gesture-pixel-art
https://twitter.com/neonslice/status/14125349813527320.8822
 */
public class BrickBreaker extends Game {

    //Setup paddle & ball
    private Paddle p1;
    private Ball b;

    //Setup array for bricks
    //Setup integer fields for row, column, brick count
    private Bricks[][] br;

    private int row;
    private int col;
    private int bricksCount;

    //Setup waittime field
    //Value is initialized to -1 so that the cutscene does not immediately play.
    //Waittime value is only changed after a level change.
    private int waittime = -1;

    //Level field is set to first level
    private int level = 1;

    //Setup score and high score fields
    private int score;
    private static int highscore;

    //Setup random bouncing integer
    private int bounceDirection;

    //Setup labels on screen (score label, high score label, level label, cutscene, etc)
    private JLabel levelLabel;
    private JLabel scoreLabel;
    private JLabel hsLabel;
    private JLabel levelShowcase;

    //Setup Labels for brick, ball, and paddle image
    private JLabel ballImage;
    private JLabel paddleImage;
//    private JLabel brickImage;

    //Setup fonts used throughout program
    private Font font;
    private Font labelFont;

    //Setup ImageIcon for paddle image
    //Research conducted
    //Retrieved from https://stackoverflow.com/questions/21129329/load-png-as-sprite-java
    //Debugged with https://www.youtube.com/watch?v=d02PK8C5EaA&t=58s
    private ImageIcon paddleIcon = new ImageIcon(getClass().getClassLoader().getResource("Paddle.png"));
    private ImageIcon ballIcon = new ImageIcon(getClass().getClassLoader().getResource("Ball1.png"));

    private ImageIcon ballIconDead = new ImageIcon(getClass().getClassLoader().getResource("Ball2.png"));

    private ImageIcon brickIcon = new ImageIcon(getClass().getClassLoader().getResource("Brick.png"));
    public BrickBreaker() {
    }

    //Setup method that sets up the game prior to act
    public void setup() {

        setLayout(null);  // Remove layout manager for absolute positioning

        //Setup paddle
        //Establish size of paddle
        //Make it so that paddle spawns in the middle of the screen relative to field
        p1 = new Paddle();
        p1.setSize(100, 10);
        p1.setX(getFieldWidth() / 2);
        p1.setY(getFieldHeight() * 6 / 7);
        add(p1);

        //Paddle image handling
        paddleImage = new JLabel(paddleIcon);
        paddleImage.setLocation(p1.getX(), p1.getY());
        paddleImage.setSize(p1.getWidth(),p1.getHeight());
        add(paddleImage);

        //Setup and add ball
        //Establish starting position and size of ball
        b = new Ball(getFieldWidth() / 2, getFieldHeight() * 3 / 5, 20);
        add(b);

        //Ball image handling
        ballImage = new JLabel(ballIcon);
        ballImage.setLocation(b.getX(), b.getY());
        ballImage.setSize(b.getWidth(),b.getHeight());
        add(ballImage);


        //Setup bricks array (br)
        br = new Bricks[7][5];
        //Call setBricks() method to put bricks on screen
        setBricks();

        //Set delay so ball does not get too fast
        setDelay(15);

        //Call main menu method
        mainMenu();

        //Add cutscene JLabel
        levelLabel = new JLabel();
        //Research conducted on importing custom fonts into program
        //Debugged with  https://stackoverflow.com/questions/58613074/problem-reading-font-data-error-when-trying-to-load-a-ttf-file-into-my-game
        //Retrieved from https://stackoverflow.com/questions/5652344/how-can-i-use-a-custom-font-in-java
        try { //Add custom font used for cutscenes (bigger size)
            font = Font.createFont(Font.TRUETYPE_FONT, new File("Resources/VCR_OSD_MONO_1.001.otf")).deriveFont(25f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            InputStream myStream = new BufferedInputStream(new FileInputStream("Resources/VCR_OSD_MONO_1.001.otf"));
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, myStream));
        } catch (FontFormatException | IOException e) { //Try catch exception auto-generated by intellij
            throw new RuntimeException(e); //Define block of code to handle errors (FontFormatException, IOException) in the try block
        }
        try { //Add custom font used for labels (smaller size)
            labelFont = Font.createFont(Font.TRUETYPE_FONT, new File("Resources/VCR_OSD_MONO_1.001.otf")).deriveFont(9f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            InputStream myStream = new BufferedInputStream(new FileInputStream("Resources/VCR_OSD_MONO_1.001.otf"));
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, myStream));
        } catch (FontFormatException | IOException e) { //Try catch exception auto-generated by intellij
            throw new RuntimeException(e); //Define block of code to handle errors (FontFormatException, IOException) in the try block
        }
        add(levelLabel);

        // Adding score label
        scoreLabel = new JLabel();
        scoreLabel.setForeground(Color.ORANGE);
        scoreLabel.setText("Score:" + score);
        scoreLabel.setFont(labelFont); // Set font to custom label font
//        Dimension preferredSize = scoreLabel.getPreferredSize();
//        scoreLabel.setSize(preferredSize.width * 2, preferredSize.height);
//        System.out.println(preferredSize.width * 2 + "+" + preferredSize.height);
        scoreLabel.setSize(150,50);
        add(scoreLabel);
        scoreLabel.setVisible(true);
        scoreLabel.setLocation((getFieldWidth() / 2) - (scoreLabel.getWidth() / 2), p1.getY() + (scoreLabel.getHeight())/2);

        // Adding high score label
        hsLabel = new JLabel();
        hsLabel.setForeground(Color.ORANGE);
        hsLabel.setText("HS:" + highscore);
        hsLabel.setFont(labelFont); // Set font to custom label font
//        Dimension preferredSizeHS = hsLabel.getPreferredSize();
//        hsLabel.setSize(preferredSizeHS.width * 2, preferredSizeHS.height);
//        System.out.println(preferredSizeHS.width * 2 + "+" + preferredSizeHS.height);
        hsLabel.setSize(150,50);
        add(hsLabel);
        hsLabel.setVisible(true);
        hsLabel.setLocation(hsLabel.getWidth() / 10, p1.getY() + (hsLabel.getHeight())/2);

        // Adding level label
        levelShowcase = new JLabel();
        levelShowcase.setForeground(Color.ORANGE);
        levelShowcase.setText("Level:" + level);
        levelShowcase.setFont(labelFont); // Set font to custom label font
//        Dimension preferredSizeLVL = levelShowcase.getPreferredSize();
//        levelShowcase.setSize(preferredSizeLVL.width * 2, preferredSizeLVL.height);
//        System.out.println(preferredSizeLVL.width * 2 + "+" + preferredSizeLVL.height);
        levelShowcase.setSize(150,50);
        add(levelShowcase);
        levelShowcase.setVisible(true);
        levelShowcase.setLocation(getFieldWidth() - levelShowcase.getWidth(), p1.getY() + (levelShowcase.getHeight())/2);

        //Read created highscore.txt file for high score number
        //Calls ReadFile() method
        //Additional information provided above ReadFile()'s method comment
        try {
            readFile();
            hsLabel.setText("HS:" + highscore); //Updates score text
        } catch (IOException e) { //Auto-generated by Intellij
            throw new RuntimeException(e);
        }
        Random random = new Random();

    }


    //Act method executes every once in a while
    public void act() {
        Random rand = new Random();
        //Paddle & Ball image handling
        paddleImage.setLocation(p1.getX(), p1.getY());
        ballImage.setLocation(b.getX(),b.getY());
        //Detect A and D key presses to move paddle
        //Calls DKeyPressed() and AKeyPressed() methods in Game (extended)
        //Add logical operator && in condition to restrict paddle within boundaries using getter methods
        if (DKeyPressed() && p1.getX() + p1.getWidth() < getFieldWidth()) {
            p1.moveRight();
        }

        if (AKeyPressed() && p1.getX() > 0) {
            p1.moveLeft();
        }

        //Detect collision between paddle and ball using .collides() method in GameObject
        //Add condition to verify Y value
        //Call bounceY() for ball in ball class
        if (b.collides(p1) && b.getDy() > 0) {
            b.bounceY();
            bounceDirection=rand.nextInt(3);
            if (bounceDirection == 1 || bounceDirection == 2) {
                b.setDx(b.getDx());
            } else {
                b.setDx(-b.getDx());
            }
        }

        //Detect collision between ball and top of field using getter method
        //Call bounceY() for ball in ball class
        if (b.getY() <= 0) {
            b.bounceY();
        }

        //Detect collision between ball and left of field using getter method
        //Call bounceX() for ball in ball class
        if (b.getX() <= 0) {
            b.bounceX();
        }

        //Detect collision between ball and right of field using getter method
        //Add width of ball so detection so right edge does not clip out of field
        //Call bounceX() for ball in ball class
        if (b.getX() + b.getWidth() >= getFieldWidth()) {
            b.bounceX();
        }

        //Check brick collision
        //Iterate through each row and column of brick using two for loops
        //Use previously established fields of row and col
        for (int i = 0; i < col; ++i) {
            for (int j = 0; j < row; ++j) {
                if (br[i][j].collides(b)) { //Check collision with collides()
                    br[i][j].move(2000, 2000); //move bricks off-screen
                    br[i][j].getBrickImage().setLocation(2000,2000);
                    remove(br[i][j].getBrickImage());  // Remove the brick image from the game
                    remove(br[i][j]); //Remove the brick that was collided with

                    //Setup bouncing randomness
                    b.bounceY();
                    bounceDirection=rand.nextInt(3);
                    if (bounceDirection == 1 || bounceDirection == 2) {
                        b.setDx(b.getDx());
                    } else {
                        b.setDx(-b.getDx());
                    }
                    bricksCount--; //Increment bricksCount field (used to detect new level)
                    score += 10; //Increment score by 10 per brick
                    scoreLabel.setText("Score:" + score); //Update score label with new score
                }
            }
        }

        //Check whether player has lost the game by calling the gameOver() method in a conditional statement
        if (gameOver()) {
            //Stop game when game over is true
            stopGame();

            //Set 'dead' ball icon
             ballImage.setIcon(ballIconDead);

            //Call hsUpdate at the start of gameOver method
            //Logs the score and compares it to high score
            try {
                hsUpdate();
            } catch (IOException e) { //Try catch exception generated by Intellij
                throw new RuntimeException(e); //Define block of code to handle errors in the try block
            }
            //Call restartMenu method to allow player to continue playing or quit
            restartMenu();
        }

        //Increment to new level when all bricks are destroyed
        if (bricksCount == 0) {
            cutscene(); //Call cutscene method to play cutsceene, increments timer
            bricksCount = -1; //Set bricksCount to -1 to ensure that cutscene is not played again
        }
        //Conditional statement in act method which increments cutscene time
        if (waittime > 0) {
            waittime--;
        } else if (waittime == 0) { //Check when waittime reaches 0 according to act timer
            setupNewLevel(); //Call setupNewLevel() to print bricks, reset positions, etc
            waittime = -1; //Set waittime to -1 to ensure that code block is not executed again
        }
    }

    //Main method
    public static void main(String[] args)  {
        BrickBreaker b = new BrickBreaker();
        b.setSize(760, 600);
        b.setVisible(true);
        b.initComponents();
    }

    /***
     * GameOver method to check death
     * @return true or false
     */
    public boolean gameOver() {
        //Check if ball's y exceeds that of paddle + paddle's height at the bottom
        if (b.getY() >= p1.getY() + p1.getHeight()) {
            return true;
        } else {
            return false;
        }
    }

    //Cutscene method to transition between levels
    //Only called when bricksCount = 0;
    //Uses previously created levelLabel

    /***
     *  Cutscene method to transition between levels
     *  Only called when bricksCount = 0;
     *  Uses previously created levelLabel
     */
    public void cutscene() {
        Color c = new Color(102,30,12);
        levelLabel.setForeground(c);
        levelLabel.setSize(400, 230);
        //Centers levelLabel relative to field size
        levelLabel.setLocation((getFieldWidth() / 2) - (levelLabel.getWidth() / 2), 0);
        //Use HTML to center level label
        levelLabel.setText("<html> <div style='text-align: center;'> " +
                "LEVEL " + level + " COMPLETED! \n" +
                "SPEED HAS BEEN INCREASED \n" + "</b>" +
                "GET READY..." + "</b>" +
                "</div></html>");
        levelLabel.setVisible(true);
        //Set font of level label to previously created font (not labelFont)
        levelLabel.setFont(font);
        //Reset position of paddle and ball
        //Freeze paddle and ball using setter methods in their respective classes
        p1.setX(getFieldWidth() / 2 - p1.getWidth() / 2);
        p1.setY(getFieldHeight() * 6 / 7);
        b.setX(getFieldWidth() / 2 - b.getWidth());
        b.setY(getFieldHeight() * 3 / 5);
        b.setBallPaused(true);
        p1.setPaddlePaused(true);
        //Set waittime to 120, to be incremented by waitime-- in act()
        waittime = 120;


    }

    /***
     * setBricks method to put bricks on screen
     */
    public void setBricks() {
        //Sets row and col fields to lengths of the br array (setup earlier)
        col = br.length;
        row = br[0].length;
        bricksCount = row * col;
        //Center bricks on the field relative to field width
        int x = ((getFieldWidth() + 22) - (80 * col)) / 2;
        //Use two for loops incrementing up to row and col fields
        //Use incrementing variables i and j in br array to setup the brick objects
        //Increment position of brick object with each loop using compound assignment operators
        //to prevent the bricks from stacking on top of each other
        for (int i = 0; i < col; ++i) {
            int y = 22;
            for (int j = 0; j < row; ++j) {
                br[i][j] = new Bricks(brickIcon);
                add(br[i][j]);
                add(br[i][j].getBrickImage());
                br[i][j].setLocation(x, y);
                br[i][j].setSize(60, 30);
                y += 60;
            }
            x += 80;
        }
    }

    /***
     * setupNewLevel method for building new level after cutscene
     */
    public void setupNewLevel() {
        b.justifyDirection(); //Makes sure ball goes towards paddle with justifyDirection() method in ball
        //Unpause the ball and paddle using the setter methods after waittime from cutscene is up
        b.setBallPaused(false);
        p1.setPaddlePaused(false);
        //Speed up the ball and paddle
        b.accelerate();
        p1.setPaddleSpeed(p1.getPaddleSpeed() + b.getAccel());
        //Debugging paddle method - resets state of keypresses using method in Game
        resetPaddle();
        setBricks();
        levelLabel.setVisible(false);
        level++;
        levelShowcase.setText("Level:" + level); //Update level label on screen
    }

    /***
     * resetLevel method for first level after a game over
     * Reset position of paddle and ball using setter methods
     * Reset state of keypresses in paddle
     * Reset level and score
     * Update labels of score and level
     */
    public void resetLevel() {
        Random rand = new Random();
        bounceDirection = rand.nextInt(2);
        //Reset position of paddle and ball using setter methods
        p1.setX(getFieldWidth() / 2 - (p1.getWidth() / 2));
        p1.setY(getFieldHeight() * 6 / 7);
        p1.setPaddleSpeed(8);
        b.setX(getFieldWidth() / 2);
        b.setY(getFieldHeight() * 3 / 5);
        if (bounceDirection == 1) b.setDx(4);
        else b.setDx(-4);
        b.setDy(4);
        ballImage.setIcon(ballIcon);
        resetPaddle(); //Reset state of keypresses in paddle
        setBricks();
        //Reset level and score
        level = 1;
        score = 0;
//        System.out.println("POST RESET SCORE " + score);
//        System.out.println("POST RESET HS: " + highscore);
        //Update labels of score and level
        scoreLabel.setText("Score:" + score);
        levelShowcase.setText("Level:" + level);
    }

    /***
     * Method to update high score by comparing ending score with current standing high score
     * Called when player loses and score is finalized
     * File is overwritten if new score exceeds current high score
     * Research and sources used
     * https://www.w3schools.com/java/java_files_create.asp
     * https://www.digitalocean.com/community/tutorials/java-write-to-file
     * @throws IOException
     */
    public void hsUpdate() throws IOException {
//        System.out.println("SCORE " + score);
//        System.out.println("HS: " + highscore);
        if (score > highscore) {
//            System.out.println("SCORE: " + score);
//            System.out.println("HS: " + highscore);
            File file = new File("highscore.txt");
            FileWriter writer = new FileWriter(file);
            highscore = score;
            writer.write(String.valueOf(score));
            hsLabel.setText("HS:" + highscore);
            writer.close();
        }
    }

    public void clearHS() throws IOException {
        File file = new File("highscore.txt");
        FileWriter writer = new FileWriter(file);
//        score = 0;
        highscore = 0;
//        System.out.println("ClearHS SCORE: " + score);
//        System.out.println("ClearHS HS: " + highscore);
        writer.write("0");
        writer.close();
        hsLabel.setText("HS:" + highscore);
    }

    /***
     * readFile() method to retrieve existing high score from file
     * Called in game setup, sets highscore field to number in file
     * @throws IOException
     */
    public static void readFile() throws IOException {
        File file = new File("highscore.txt");
        if (file.exists()) { //Condition to check whether highscore file already exists
            Scanner sc = new Scanner(file);
            if (sc.hasNextInt()) { //Scanner checks value inside file
                highscore = sc.nextInt();
            } else { //If no value found, new writer is created and 0 is written into the file
                FileWriter write = new FileWriter("highscore.txt", false);
                write.write("0");
                write.close();
            }
        } else {
            file.createNewFile(); //If no highscore file already exists, a new one is created
            FileWriter write = new FileWriter("highscore.txt", false);
            write.write("0"); //0 is also written into the new file
            write.close();
        }
    }

    /***
     * mainMenu() method for setting up JOptionPane for game introduction screen
     * Research conducted
     * Retrieved from https://mkyong.com/swing/java-swing-joptionpane-showoptiondialog-example/+
     */
    public void mainMenu() {
        //Create array for available options in JOptionPane
        String[] options = {"Start", "Close", "Instructions"};
        int input = JOptionPane.showOptionDialog(getContentPane(), "<html><h1 style = 'text-align:right;'>Welcome to Prison Break!</h1></html>",
                "Prison Break", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);
        //Check for No option in array
        if (input == 1) {
            stopGame(); //Stop game if player presses "no"
            setVisible(false); //Set field to invisible
            System.exit(0); //Close game
        }
        //Check for Instructions option in array
        if (input == 2) {
            JOptionPane.showMessageDialog(getContentPane(), //Use HTML to format instructions (header, breaks, etc)
                    "<html> <b> <div style='text-align: center;'>" +
                            "<h1> HOW TO PLAY </h1> </b> </div>" +
                            "▪ To play, <b> destroy </b> all the bricks on your screen with your ball. <br/> <br/> " +
                            "▪ Use A to move your paddle <b> LEFT </b> <br/> <br/>" +
                            "▪ use D to move your paddle <b> RIGHT </b> <br/> <br/>" +
                            "▪ Break all the bricks to advance in level! <br/> <br/>" +
                            "▪ Each level advances the <b> speed </b> of the ball. <br/> <br/>" +
                            "▪ However, your paddle also increases as compensation. <br/> <br/>" +
                            "▪ <b> Good luck on breaking out! </b> <br/> <br/> </html>");
            mainMenu();
        }

    }

    /***
     * restartMenu() method to display JOptionPane on game over
     */
    public void restartMenu() {
        String[] options = {"Start", "Close", "Reset high score"};
        //Uses HTML to arrange text on JOptionPane
        int input = JOptionPane.showOptionDialog(getContentPane(),
                "<html> ▪ You have died. <br/>" +
                        "▪ your score was: " + score +
                        "<br/>▪ Would you like to play again? <br/>",
                "Prison Break", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options, options[0]);
        System.out.println("RESTART MENU INPUT: " + input);
        if (input == JOptionPane.NO_OPTION) { //Closes game if player selects no
            setVisible(false);
            System.exit(0);
        } else if (input == JOptionPane.YES_OPTION) {
            //Iterates through existing bricks
            //Removes all bricks to prepare for resetLevel() method, which builds new ones
            for (int i = 0; i < col; ++i) {
                for (int j = 0; j < row; ++j) {
                    br[i][j].move(2000, 2000);
                    br[i][j].getBrickImage().setLocation(2000,2000);
                    remove(br[i][j].getBrickImage());  // Remove the brick image from the game
                    remove(br[i][j]); //Remove the brick that was collided with
                }
            }
            //Call resetLevel() method to reset position of paddle and ball
            //Reset speed of ball, reset paddle state, reset level and score, and reset labels.
            resetLevel();
            startGame();
        } else if (input == 2){
            try {
                clearHS(); // Try clearing the high score
                restartMenu();
            } catch (IOException e) {
                e.printStackTrace(); // Print the error if something goes wrong
                JOptionPane.showMessageDialog(getContentPane(), "Error clearing high score. Please try again.");
            }
        }
    }

}



